In [1]:
import pandas as pd

df = pd.read_csv('../../output_data/4_2_vectorized_ds.csv')

df.info(5)

KeyboardInterrupt:

In [ ]:
import pandas as pd

df = pd.read_csv('../../output_data/4_2_vectorized_ds.csv')

df.info(5)

KeyboardInterrupt:

In [ ]:
import pandas as pd

df = pd.read_csv('../../output_data/4_2_vectorized_ds.csv')

df.info(5)

KeyboardInterrupt:

In [2]:
df.head(5)

,Unnamed: 0,input_0,input_1,input_2,input_3,input_4,input_5,input_6,input_7,input_8,...,input_13194,input_13195,input_13196,input_13197,input_13198,input_13199,tag,lemmatized,lemmatized_no_numbers,vectorized
0,0,0.187500,0.015747,-0.058594,0.083496,-0.063477,0.122559,0.127930,0.002411,0.263672,...,NaN,NaN,NaN,NaN,NaN,NaN,COMMUNITY,"['personal', 'ranking', 'community', 'use', 'a...","['personal', 'ranking', 'community', 'use', 'a...","[array([ 0.1875 , 0.01574707, -0.05859375,..."
1,1,0.113770,0.110840,0.043213,-0.194336,0.140625,-0.460938,0.022217,-0.084961,-0.047852,...,NaN,NaN,NaN,NaN,NaN,NaN,ENVIRONMENT,"['took', '30', 'year', 'climate', 'tech', 'inv...","['took', 'number', 'year', 'climate', 'tech', ...","[array([ 0.11376953, 0.11083984, 0.04321289,..."
2,2,-0.051025,0.045898,-0.273438,-0.259766,0.347656,0.026611,-0.217773,-0.182617,-0.247070,...,NaN,NaN,NaN,NaN,NaN,NaN,RELAX,"['rain', 'sitting', 'car']","['rain', 'sitting', 'car']","[array([-5.10253906e-02, 4.58984375e-02, -2.7..."
3,3,0.208008,-0.076660,-0.000389,0.123535,0.316406,-0.281250,0.251953,-0.326172,0.026123,...,NaN,NaN,NaN,NaN,NaN,NaN,TRAVEL,"['cassis', 'worth', 'staying']","['cassis', 'worth', 'staying']","[array([ 2.08007812e-01, -7.66601562e-02, -3.8..."
4,4,0.011292,0.028931,0.083496,-0.049805,-0.130859,-0.109863,-0.115234,-0.074707,-0.089355,...,NaN,NaN,NaN,NaN,NaN,NaN,ASTRONOMY,"['new', 'research', 'suggests', 'black', 'hole...","['new', 'research', 'suggests', 'black', 'hole...","[array([ 1.12915039e-02, 2.89306641e-02, 8.3..."

In [5]:
# Transform TAG to numerical value

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


df['TAG_transformed'] = le.fit_transform(df['tag'])

In [6]:
df.head(3)

,Unnamed: 0,input_0,input_1,input_2,input_3,input_4,input_5,input_6,input_7,input_8,...,input_13195,input_13196,input_13197,input_13198,input_13199,tag,lemmatized,lemmatized_no_numbers,vectorized,TAG_transformed
0,0,0.187500,0.015747,-0.058594,0.083496,-0.063477,0.122559,0.127930,0.002411,0.263672,...,NaN,NaN,NaN,NaN,NaN,COMMUNITY,"['personal', 'ranking', 'community', 'use', 'a...","['personal', 'ranking', 'community', 'use', 'a...","[array([ 0.1875 , 0.01574707, -0.05859375,...",4
1,1,0.113770,0.110840,0.043213,-0.194336,0.140625,-0.460938,0.022217,-0.084961,-0.047852,...,NaN,NaN,NaN,NaN,NaN,ENVIRONMENT,"['took', '30', 'year', 'climate', 'tech', 'inv...","['took', 'number', 'year', 'climate', 'tech', ...","[array([ 0.11376953, 0.11083984, 0.04321289,...",10
2,2,-0.051025,0.045898,-0.273438,-0.259766,0.347656,0.026611,-0.217773,-0.182617,-0.247070,...,NaN,NaN,NaN,NaN,NaN,RELAX,"['rain', 'sitting', 'car']","['rain', 'sitting', 'car']","[array([-5.10253906e-02, 4.58984375e-02, -2.7...",26